trigger:
- master

jobs:

- job: 'Testing_ptr_Mac'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
        ci.env: 'py36'
      Python36Integration:
        python.version: '3.6'
        ci.env: 'PTR_INTEGRATION'
      Python37:
        python.version: '3.7'
        ci.env: 'py37'
      Python37Integration:
        python.version: '3.7'
        ci.env: 'PTR_INTEGRATION'

- job: 'Testing_ptr_Windows'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
        ci.env: 'py36'
      Python36Integration:
        python.version: '3.6'
        ci.env: 'PTR_INTEGRATION'
        pythonioencoding: 'utf-8'
      Python37:
        python.version: '3.7'
        ci.env: 'py37'
      Python37Integration:
        python.version: '3.7'
        ci.env: 'PTR_INTEGRATION'
        pythonioencoding: 'utf-8'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python ci.py
    displayName: 'Running CI for $(ci.env)'
